#: schema https://esm.sh/wrangler/config-schema.json
# https://developers.cloudflare.com/workers/wrangler/configuration

name = "honox-mdx-islands"
compatibility_date = "2025-02-09"
pages_build_output_dir = "./dist"
compatibility_flags = [ "nodejs_compat" ]

[build]
command = "vite build --mode='client' && vite build"

# https://developers.cloudflare.com/workers/observability/logs/workers-logs/
[observability]
enabled = true

[vars]
BUN_VERSION = "1.2.2"