name: Publish

on:
  push:
    branches: ['main']
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  ACTIONS_RUNNER_DEBUG: true

jobs:
  ci:
    name: 'PUBLISH SITE'
    timeout-minutes: 3
    runs-on: ['ubuntu-latest']
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Setup Bun'
        uses: oven-sh/setup-bun@main
        with:
          bun-version: 'latest'

      - name: 'Install Dependencies'
        run: bun install --frozen-lockfile

      - name: '🔶 Publish - Cloudflare Workers'
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          bun x wrangler@latest pages deploy dist --project-name='honox-mdx-islands'
